# Generated by Django 2.2 on 2021-05-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='not defined', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UserName', max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='0 hr 15 min', max_length=1000)),
                ('phone', models.CharField(default='7775556881', max_length=1000)),
                ('description', models.CharField(default='some descrip lorem is', max_length=1000)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User2')),
            ],
        ),
    ]
